Add the ability to mock the RECONNECT message
fdgt-apis/api pull request #167
Opened 2021-01-09 12:30 UTC by pajlada

https://dev.twitch.tv/docs/irc/commands#reconnect-twitch-commands

This may be more targeted towards Twitch IRC library creators than bot creators, but it's a useful response to test nonetheless

2021-01-13 18:14 UTC, trezy commented
@pajlada Sorry I didn't see this sooner! I'll pull it down and give it a peek this afternoon, then hopefully get it merged! 😁

2021-01-13 22:19 UTC, trezy commented
@pajlada The only issue I have right now is that the `RECONNECT` message is currently handled the same way normal messages are, rather than the way that system messages are. For example, if you send a `/ping` command, it's handled specially by the [`handlePINGMessage`](https://github.com/fdgt-apis/api/blob/main/src/helpers/handlePINGMessage.js) helper. With the way that the reconnect is being handled in your PR, the response gets pushed through the `renderMessage` helper unnecessarily, causing a superfluous `@` to be appended to the response.

I'd prefer that we move the handling of the reconnects into a method on the connection (`connection.sendReconnect`, similar to [`connection. sendUnknownCommand`](https://github.com/fdgt-apis/api/blob/main/src/structures/Connection.js#L341-L343)). Something like this:

```js
sendReconnect = () => {
	incrementStat('reconnects')
	this.send('RECONNECT')
}
```

That means we'll also have to add special handling for the reconnect message. We can do that in [`handlePRIVMessage`](), right after [line 45](https://github.com/fdgt-apis/api/blob/main/src/helpers/handlePRIVMSGMessage.js#L45) where we parse the message:

```js
if (command.toLowerCase().trim() === 'reconnect') {
	return connection.sendReconnect('RECONNECT')
}
```

2021-01-16 11:40 UTC, pajlada commented
@trezy Thanks for your feedback! I implemented the code changes as you suggested and the tests still work! :slightly_smiling_face:

2021-01-18 04:35 UTC, trezy requested changes
Added one last comment, but the rest of it looks great! Once you clean that up we can merge.

2021-01-18 04:35 UTC, trezy commented on src/helpers/handlePRIVMSGMessage.js
> +		return connection.sendReconnect('RECONNECT')
One last nitpick: `sendReconnect` doesn't take any arguments, so we can remove the string that gets passed in.

2021-01-30 14:47 UTC, trezy approved these changes
LGTM!

2021-02-03 20:02 UTC, merged